
title: My Sophmore Ap Computer Science Webstie
author: Aaditya Pemmaraju
email: apemmaraju2@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  I am a sophmore in high school and this webstie was made for my AP Comp Sci final project. 
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
