
title: My Sophmore Ap Computer Science Webstie Welcome to my website! My name is Aaditya Pemmaraju and this my AP Computer Science Website. It contains my social medai information, a brag sheet about my accomplishments and an image of me
author: Aaditya Pemmaraju
email: apemmaraju2@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  I am a sophmore in high school and this webstie was made for my AP Comp Sci final project. 
  
My bragsheet: Well to start off I play the piano, I played the piano ever since I was about 4 years old but I seriously got into it every since I was 10. 
theme: minima
# social links
twitter_username: apepxm2 # DO NOT include the @ character, or else the build will fail!


show_excerpts: true # set to false to remove excerpts on the homepage
