
title: My Junior year Ap Computer Science Website Welcome to my website! My name is Aaditya Pemmaraju and this my AP Computer Science Website. It contains my social media information, a brag sheet about my accomplishments and an image of me
author: Aaditya Pemmaraju
email: apemmaraju2@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  I am a junior in high school and this webstie was made for my AP Comp Sci final project. I linked my twitter just click on the username.
  

theme: minima
# social links
twitter_username: apepxm2 # DO NOT include the @ character, or else the build will fail!


show_excerpts: true # set to false to remove excerpts on the homepage
